// <auto-generated />
namespace KidKinderProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migupdatebookaseat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migupdatebookaseat));
        
        string IMigrationMetadata.Id
        {
            get { return "202402290914426_mig-update-bookaseat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
