// <auto-generated />
namespace KidKinderProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_createdb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_createdb));
        
        string IMigrationMetadata.Id
        {
            get { return "202402071311510_mig_createdb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
